const state={songs:[],view:'home',current:null,index:-1,queue:[],queueIndex:-1,shuffle:false,repeat:0,favorites:JSON.parse(localStorage.getItem('swaraj-favorites')||'[]'),yt:null,ytReady:false,mode:'music',adminToken:localStorage.getItem('swaraj-admin-token')||''};
const $=s=>document.querySelector(s), audio=$('#audio');
const E={cover:$('#cover'),title:$('#title'),artist:$('#artist'),fullCover:$('#fullCover'),fullTitle:$('#fullTitle'),fullArtist:$('#fullArtist'),play:$('#play'),fullPlay:$('#fullPlay'),prev:$('#prev'),next:$('#next'),fullPrev:$('#fullPrev'),fullNext:$('#fullNext'),seek:$('#seek'),cur:$('#cur'),dur:$('#dur'),volume:$('#volume'),queue:$('#queue'),toast:$('#toast'),videoWrap:$('#ytPlayerWrap'),videoMode:$('#videoMode'),musicMode:$('#musicMode'),source:$('#sourceBadge')};
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(msg){E.toast.textContent=msg;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),2800)}
function img(song){return song.cover_url||`/api/cover/${encodeURIComponent(song.category||'All Songs')}`}
function fav(song){return state.favorites.includes(String(song.id))||state.favorites.includes(song.id)}
function saveFav(){localStorage.setItem('swaraj-favorites',JSON.stringify(state.favorites));const likedEl=$('#likedCount'); if(likedEl) likedEl.textContent=state.favorites.length}
function toggleFav(song){const id=String(song.id),i=state.favorites.indexOf(id);if(i<0){state.favorites.push(id);toast('Added to liked songs')}else{state.favorites.splice(i,1);toast('Removed from liked songs')}saveFav();renderAll()}
async function json(url,opt={}){const r=await fetch(url,{cache:'no-store',...opt});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function load(){try{const [songs,cats]=await Promise.all([json('/api/songs'),json('/api/categories')]);state.songs=songs.songs||[];renderCategories(cats.categories||[]);renderAll();$('#count').textContent=state.songs.length;$('#ytCount').textContent=state.songs.filter(s=>s.source_type==='youtube').length;$('#mp3Count').textContent=state.songs.filter(s=>s.source_type==='mp3').length;$('#catCount').textContent=(cats.categories||[]).length;renderSide(cats.categories||[]);loadYoutube();}catch(e){console.error(e);toast(e.message);['homeSongs','musicSongs','youtubeSongs','librarySongs','favoriteSongs'].forEach(id=>{const el=$('#'+id);if(el)el.innerHTML=`<div class="panel glass">Unable to load: ${esc(e.message)}</div>`})}}
async function loadYoutube(){try{const d=await json('/api/youtube');renderInto($('#youtubeSongs'),d.songs||[])}catch(e){console.error(e)}}
function renderCategories(cats){$('#categories').innerHTML=cats.length?cats.map(c=>`<article class="category" data-cat="${esc(c.name)}"><div class="symbol">${symbol(c.name)}</div><h3>${esc(c.name)}</h3><p>${c.count} songs · ${c.youtube||0} YouTube</p></article>`).join(''):`<div class="panel glass">No categories yet.</div>`;document.querySelectorAll('.category').forEach(x=>x.onclick=()=>filterCategory(x.dataset.cat))}
function renderSide(cats){$('#sideCategories').innerHTML=cats.map(c=>`<button data-cat="${esc(c.name)}">${esc(c.name)} <small>${c.count}</small></button>`).join('');document.querySelectorAll('.side-cats button').forEach(x=>x.onclick=()=>filterCategory(x.dataset.cat))}
function symbol(n){const x=n.toLowerCase();if(x.includes('love'))return'♥';if(x.includes('bhakti')||x.includes('ganpati'))return'ॐ';if(x.includes('marathi'))return'म';if(x.includes('energy'))return'⚡';if(x.includes('emotional'))return'◒';return'♫'}
function card(song){const youtube=song.source_type==='youtube';return `<article class="song-card"><div class="art"><img src="${esc(img(song))}" onerror="this.style.display='none'" alt=""><span class="source">${youtube?'▶ YOUTUBE':'♫ MP3'}</span></div><div class="body"><h3>${esc(song.title)}</h3><p>${esc(song.artist||'SwarAJ')} · ${esc(song.category||'All Songs')}</p><div class="card-actions"><button class="play-now" data-play="${esc(song.id)}">▶ Play</button><button data-fav="${esc(song.id)}">${fav(song)?'♥':'♡'}</button></div></div></article>`}
function renderInto(el,songs){if(!el)return;el.innerHTML=songs.length?songs.map(card).join(''):`<div class="panel glass">No songs found.</div>`;el.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playById(b.dataset.play));el.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const s=state.songs.find(x=>String(x.id)===String(b.dataset.fav));if(s)toggleFav(s)})}
function renderAll(){renderInto($('#homeSongs'),state.songs.slice(0,24));renderInto($('#musicSongs'),state.songs.filter(s=>s.source_type==='mp3'));renderInto($('#youtubeSongs'),state.songs.filter(s=>s.source_type==='youtube'));renderInto($('#librarySongs'),state.songs);renderInto($('#favoriteSongs'),state.songs.filter(fav));const likedEl=$('#likedCount'); if(likedEl) likedEl.textContent=state.favorites.length}
function filterCategory(cat){state.view='music';showView('music');const list=state.songs.filter(s=>s.category===cat);renderInto($('#musicSongs'),list);toast(`${cat}: ${list.length} songs`)}
function search(q){const v=q.trim().toLowerCase();$('#clear').hidden=!v;if(!v){$('#searchResults').hidden=true;return}const list=state.songs.filter(s=>[s.title,s.artist,s.album,s.category,s.language].some(x=>String(x||'').toLowerCase().includes(v)));$('#searchResults').hidden=false;$('#resultTitle').textContent=`${list.length} result${list.length===1?'':'s'} for “${q}”`;renderInto($('#results'),list);window.scrollTo({top:0,behavior:'smooth'})}
function showView(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.hidden=true);const el=$(`#${view}View`);if(el)el.hidden=false;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='admin')loadAdminSongs()}
function stopYouTube(){if(state.yt&&state.yt.stopVideo)try{state.yt.stopVideo()}catch(_){} }
function ensureYT(){if(state.ytReady)return Promise.resolve();return new Promise(resolve=>{if(window.YT&&window.YT.Player){state.ytReady=true;return resolve()}const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{state.ytReady=true;old?.();resolve()};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s)})}
async function playYouTube(song){await ensureYT();audio.pause();audio.removeAttribute('src');if(!state.yt){state.yt=new YT.Player('ytPlayer',{height:'100%',width:'100%',videoId:song.youtube_id,playerVars:{autoplay:1,playsinline:1,rel:0,modestbranding:1},events:{onReady:e=>e.target.playVideo(),onStateChange:onYTState,onError:e=>toast(`YouTube player error: ${e.data}`)}})}else{state.yt.loadVideoById(song.youtube_id)}setMode('music');E.videoMode.hidden=false;E.source.textContent='YOUTUBE';updatePlayer(song);}
function onYTState(e){if(e.data===YT.PlayerState.PLAYING){setPlaying(true)}if(e.data===YT.PlayerState.ENDED)nextSong()}
function playMp3(song){stopYouTube();audio.src=song.audio_url||song.url;audio.load();audio.play().then(()=>setPlaying(true)).catch(e=>{console.error(e);toast('Unable to play MP3. Check the file URL.')});setMode('music');E.videoMode.hidden=true;E.source.textContent='MP3';updatePlayer(song)}
function playById(id){const index=state.songs.findIndex(s=>String(s.id)===String(id));if(index<0)return;state.current=state.songs[index];state.index=index;if(!state.queue.length){state.queue=[...state.songs];state.queueIndex=index}else{state.queueIndex=Math.max(0,state.queue.findIndex(s=>String(s.id)===String(id)))}state.current.source_type==='youtube'?playYouTube(state.current):playMp3(state.current);renderQueue()}
function updatePlayer(song){E.title.textContent=song.title;E.artist.textContent=song.artist||'SwarAJ';E.fullTitle.textContent=song.title;E.fullArtist.textContent=song.artist||'SwarAJ';E.cover.src=img(song);E.fullCover.src=img(song);E.like.textContent=fav(song)?'♥':'♡';document.title=`${song.title} — स्वरAJ`}
function setPlaying(on){E.play.textContent=on?'Ⅱ':'▶';E.fullPlay.textContent=on?'Ⅱ':'▶'}
function togglePlay(){if(!state.current){if(state.songs[0])playById(state.songs[0].id);return}if(state.current.source_type==='youtube'){const p=state.yt?.getPlayerState?.();if(p===YT.PlayerState.PLAYING){state.yt.pauseVideo();setPlaying(false)}else{state.yt.playVideo();setPlaying(true)}}else if(audio.paused)audio.play().then(()=>setPlaying(true));else audio.pause()}
function nextSong(){if(!state.queue.length)return;if(state.repeat===1){return state.current.source_type==='youtube'?state.yt?.seekTo(0):((audio.currentTime=0),audio.play())}let i;if(state.shuffle)i=Math.floor(Math.random()*state.queue.length);else{i=state.queueIndex+1;if(i>=state.queue.length){if(state.repeat===2)i=0;else return}}state.queueIndex=i;const s=state.queue[i];state.current=s;state.index=state.songs.findIndex(x=>String(x.id)===String(s.id));s.source_type==='youtube'?playYouTube(s):playMp3(s);renderQueue()}
function previousSong(){if(state.current?.source_type==='mp3'&&audio.currentTime>3){audio.currentTime=0;return}if(state.current?.source_type==='youtube'&&state.yt?.getCurrentTime()>3){state.yt.seekTo(0);return}if(!state.queue.length)return;let i=state.queueIndex-1;if(i<0)i=state.queue.length-1;state.queueIndex=i;const s=state.queue[i];state.current=s;s.source_type==='youtube'?playYouTube(s):playMp3(s)}
function setMode(mode){state.mode=mode;E.musicMode.classList.toggle('active',mode==='music');E.videoMode.classList.toggle('active',mode==='video');E.videoWrap.classList.toggle('hidden',!(mode==='video'&&state.current?.source_type==='youtube'));if(mode==='video')E.fullPlayer.classList.add('open');}
function renderQueue(){E.queue.innerHTML=state.queue.map((s,i)=>`<div class="queue-row" data-q="${i}"><img src="${esc(img(s))}" onerror="this.style.display='none'"><div><b>${esc(s.title)}</b><br><small>${s.source_type==='youtube'?'YouTube':'MP3'} · ${esc(s.artist||'SwarAJ')}</small></div></div>`).join('');E.queue.querySelectorAll('[data-q]').forEach(x=>x.onclick=()=>{const i=Number(x.dataset.q);state.queueIndex=i;const s=state.queue[i];playById(s.id)})}
function loadAdminSongs(){const token=state.adminToken;if(!token){$('#adminStatus').textContent='Enter ADMIN_TOKEN';return}fetch('/api/admin/songs',{headers:{'x-admin-token':token}}).then(r=>r.json()).then(d=>{if(!d.success)throw Error(d.error);$('#adminStatus').textContent=`Connected · ${d.count} songs`;$('#adminSongs').innerHTML=d.songs.map(s=>`<div class="admin-row"><span>${esc(s.title)} <small>(${s.source_type})</small></span><button data-del="${s.id}">Delete</button></div>`).join('');$('#adminSongs').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteAdmin(b.dataset.del))}).catch(e=>{$('#adminStatus').textContent=e.message})}
async function deleteAdmin(id){if(!confirm('Delete this song?'))return;try{await json(`/api/admin/songs/${id}`,{method:'DELETE',headers:{'x-admin-token':state.adminToken}});toast('Song deleted');load();loadAdminSongs()}catch(e){toast(e.message)}}
async function submitYT(e){e.preventDefault();if(!state.adminToken)return toast('Connect admin first');const fd=new FormData(e.target);fd.append('source_type','youtube');try{const d=await json('/api/admin/songs',{method:'POST',headers:{'x-admin-token':state.adminToken},body:fd});toast(`Added ${d.song.title}`);e.target.reset();load();loadAdminSongs()}catch(err){toast(err.message)}}
async function submitMP3(e){e.preventDefault();if(!state.adminToken)return toast('Connect admin first');const fd=new FormData(e.target);fd.append('source_type','mp3');try{const d=await json('/api/admin/upload',{method:'POST',headers:{'x-admin-token':state.adminToken},body:fd});toast(`Uploaded ${d.song.title}`);e.target.reset();load();loadAdminSongs()}catch(err){toast(err.message)}}
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>showView(n.dataset.view));$('#search').oninput=e=>search(e.target.value);$('#clear').onclick=()=>{$('#search').value='';search('')};$('#refresh').onclick=load;$('#showAll').onclick=()=>{showView('home');renderAll()};$('#playAll').onclick=()=>state.songs[0]&&playById(state.songs[0].id);$('#shuffleAll').onclick=()=>{state.shuffle=true;nextSong()};E.play.onclick=togglePlay;E.fullPlay.onclick=togglePlay;E.prev.onclick=previousSong;E.fullPrev.onclick=previousSong;E.next.onclick=nextSong;E.fullNext.onclick=nextSong;E.like.onclick=()=>state.current&&toggleFav(state.current);$('#expand').onclick=()=>E.fullPlayer.classList.toggle('open');$('#musicMode').onclick=()=>setMode('music');$('#videoMode').onclick=()=>setMode('video');$('#shuffle').onclick=()=>{state.shuffle=!state.shuffle;toast(state.shuffle?'Shuffle on':'Shuffle off')};$('#repeat').onclick=()=>{state.repeat=(state.repeat+1)%3;toast(['Repeat off','Repeat one','Repeat all'][state.repeat])};$('#clearQueue').onclick=()=>{state.queue=[];state.queueIndex=-1;renderQueue();toast('Queue cleared')};$('#volume').oninput=e=>{audio.volume=Number(e.target.value);if(state.yt?.setVolume)state.yt.setVolume(Number(e.target.value)*100)};audio.volume=.8;audio.addEventListener('timeupdate',()=>{E.cur.textContent=fmt(audio.currentTime);if(audio.duration){E.dur.textContent=fmt(audio.duration);E.seek.value=audio.currentTime/audio.duration*100}});audio.addEventListener('loadedmetadata',()=>E.dur.textContent=fmt(audio.duration));audio.addEventListener('play',()=>setPlaying(true));audio.addEventListener('pause',()=>setPlaying(false));audio.addEventListener('ended',nextSong);E.seek.oninput=e=>{if(state.current?.source_type==='mp3'&&audio.duration)audio.currentTime=audio.duration*Number(e.target.value)/100};setInterval(()=>{if(state.current?.source_type==='youtube'&&state.yt?.getCurrentTime){const c=state.yt.getCurrentTime(),d=state.yt.getDuration();E.cur.textContent=fmt(c);E.dur.textContent=fmt(d);E.seek.value=d?c/d*100:0}},500);$('#saveToken').onclick=()=>{state.adminToken=$('#adminToken').value.trim();localStorage.setItem('swaraj-admin-token',state.adminToken);loadAdminSongs()};$('#adminToken').value=state.adminToken;$('#ytForm').onsubmit=submitYT;$('#mp3Form').onsubmit=submitMP3;function fmt(s){s=Number(s)||0;return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
load();
